package com.charapadev.pdv.sales.entities;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

@Schema(description = "The process about sell products")
@Entity
@Table(name = "sales")
public class Sale {

    @Schema(description = "Sale identifier", example = "2")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Schema(description = "Autogenerated value containing the total value of this sale instance", example = "544.50")
    @Column(nullable = false)
    private BigDecimal totalValue = BigDecimal.ZERO;

    @Column(nullable = false)
    private BigDecimal totalPaymentValue = BigDecimal.ZERO;

    @Schema(description = "Indicate if the sale is visible on reports and statistics", example = "false")
    @Column(nullable = false)
    private boolean visible = true;

    @Schema(description = "Value that overflows the payment total value", example = "32.5")
    @Column(nullable = false)
    private BigDecimal change = BigDecimal.ZERO;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sale")
    private final Set<ItemSale> itemSales = new HashSet<>();

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sale")
    private final Set<PaymentSale> paymentSales = new HashSet<>();


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Set<ItemSale> getItemSales() {
        return itemSales;
    }

    public void addItemSales(ItemSale itemSale) {
        this.itemSales.add(itemSale);
    }

    public Set<PaymentSale> getPaymentSales() {
        return paymentSales;
    }

    public void addPaymentSales(PaymentSale paymentSale) {
        this.paymentSales.add(paymentSale);
    }

    public BigDecimal getTotalValue() {
        return totalValue;
    }

    public void setTotalValue(BigDecimal totalValue) {
        this.totalValue = totalValue;
    }

    public boolean isVisible() {
        return visible;
    }

    public void setVisible(boolean visible) {
        this.visible = visible;
    }

    public BigDecimal getChange() {
        return change;
    }

    public void setChange(BigDecimal change) {
        this.change = change;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Sale sale)) return false;
        return Objects.equals(id, sale.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }


    // Calculate the change value using the totalPaymentValue found
    private void deduceChange() {
        this.change = totalPaymentValue.subtract(totalValue);
    }


    // Increments the totalPaymentValue property with each payment method amount
    private void increasePaymentAmount(BigDecimal amount) {
        totalPaymentValue = totalPaymentValue.add(amount);
    }

    // Increments the totalValue property with each item amount
    private void increaseAmount(BigDecimal amount) {
        totalValue = totalValue.add(amount);
    }


    // Calculate the total value of items, payments and change
    public void processTotals() {
        for (ItemSale item : itemSales) {
           increaseAmount(item.getTotalPrice());
        }

        for (PaymentSale payment : paymentSales) {
            increasePaymentAmount(payment.getAmount());
        }

        this.deduceChange();
    }

}
